version: "3.9"
services:
    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "python app.py"
        volumes:
            - ./app:/src/app
        ports:
            - 80:8080
